#--------------------------------------------------------------------------
# Configuration
#--------------------------------------------------------------------------

set -g extended-keys on
setw -g mode-keys vi
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g allow-rename on
set -g renumber-windows on
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/{255}%&%d::%p1%{255}%&%d%;m'
set -as terminal-overrides ',*:Hls=\E]8;id=%p1%s;%p2%s\E\\:Hlr=\E]8;;\E\\'
set -g mouse on
set -g set-titles on
setw -g monitor-activity on
set -g bell-action any
set -g visual-bell off
set -g visual-activity off
set -g focus-events on
setw -g aggressive-resize on
set -g detach-on-destroy off
set -s escape-time 0

#--------------------------------------------------------------------------
# Status line
#--------------------------------------------------------------------------
set-option -g status-left-length 100
set-option -g status-right-length 100
set-option -g status-left " #{session_name}  "
set-option -g status-right "#{pane_title} "
set-option -g status-style "fg=#545c7e bg=default"
set-option -g window-status-format "#{window_index}\uf0ff#{pane_current_command} "
set-option -g window-status-current-format "#[fg=#545c7e]#{window_index}\uf0ff#[fg=#E9E9EA]#{pane_current_command} "
set-option -g window-status-current-style "fg=#E9E9EA"
set-option -g window-status-activity-style none
set-option -g pane-active-border-style "fg=#1f2335"
set-option -g pane-border-style "fg=#1f2335"
#--------------------------------------------------------------------------
# Key Bindings
#--------------------------------------------------------------------------
set -g prefix C-L
bind C-L send-prefix
unbind r
bind r source-file ~/.tmux.conf\; display-message '~/.tmux.conf reloaded'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind w new-window -c "#{pane_current_path}"
bind -r n next-window
bind -r p previous-window
bind -r N run-shell "tmux swap-window -t $(expr $(tmux list-windows | grep '\"(active)\"' | cut -d '\":' -f 1) + 1)"
bind -r P run-shell "tmux swap-window -t $(expr $(tmux list-windows | grep '\"(active)\"' | cut -d '\":' -f 1) - 1)"
bind-key > swap-window -t +1 \; next
bind-key < swap-window -t -1 \; prev
bind Space last-window
bind -r ] switch-client -n
bind -r [ switch-client -p

set -g allow-rename off
set -g status-position top
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
